update for rewards 2020
kongliangzhong/eth-contracts pull request #8
Opened 2021-02-18 17:28 UTC by kongliangzhong

2021-02-18 18:43 UTC, Brechtpd commented on 2020_reward_2.tsv
> +0xD984D096B4bF9DCF5fd75D9cBaf052D00EBe74c4	"616,619"	"308,310"	"308,310"
`0xD984D096B4bF9DCF5fd75D9cBaf052D00EBe74c4` is listed twice in the rewards. I assume that's an error? The current smart contracts expect the addresses to be unique, so this will give incorrect rewards for this address.

2021-02-18 18:44 UTC, Brechtpd commented on contracts/EmployeeTokenOwnershipPlan2020.sol
> +        require(_totalReward == totalReward, "VALUE_MISMATCH");
If addresses aren't unique this will not work correctly and the `totalReward` check does not catch the error.

2021-02-18 19:14 UTC, kongliangzhong commented on 2020_reward_2.tsv
> +0xD984D096B4bF9DCF5fd75D9cBaf052D00EBe74c4	"616,619"	"308,310"	"308,310"
Oh, It's should be an error, I think. will confirm this with Daniel.

2021-02-18 19:15 UTC, kongliangzhong commented on contracts/EmployeeTokenOwnershipPlan2020.sol
> +        require(_totalReward == totalReward, "VALUE_MISMATCH");
All addresses are assumed to be unique, I think.

2021-02-18 20:54 UTC, Brechtpd commented on contracts/EmployeeTokenOwnershipPlan2020.sol
> +        return records[recipient].rewarded.mul(block.timestamp.sub(vestStart)) / vestPeriod;
Oh wow, how did we miss this before, this doesn't cap the rewards after the vesting period has ended!

```
uint period = block.timestamp.sub(vestStart);
if (period > vestPeriod) {
    period = vestPeriod;
}
return records[recipient].rewarded.mul(period) / vestPeriod;
```

2021-02-18 21:13 UTC, Brechtpd commented on contracts/EmployeeTokenOwnershipPlan2020.sol
> +        records[newRecipient] = r;
We need to check here that `newRecipient` isn't already an address receiving rewards, otherwise all the existing data for that address gets overwritten. So extra like `require(records[newRecipient].rewarded == 0, 'INVALID_RECIPIENT")` is needed.

There is a similar problem in `CancellableEmployeeTokenOwnershipPlan.changeMemberAddress` but that one is only callable by the owner which has full power any way. But probably not a bad idea to add this check there as well as a check against mistakes: `require(records[newAddr].rewarded == 0, 'INVALID_RECIPIENT")`.

2021-02-19 06:23 UTC, dong77 commented on 2020_reward_2.tsv
> +0xD984D096B4bF9DCF5fd75D9cBaf052D00EBe74c4	"616,619"	"308,310"	"308,310"
Thanks, the error is fixed in my numbers file

2021-02-19 06:24 UTC, dong77 commented on contracts/EmployeeTokenOwnershipPlan2020.sol
> +        require(_totalReward == totalReward, "VALUE_MISMATCH");
We should check the new address is not yet in the record. Otherwise, the contract should throw an error.

2021-02-19 06:27 UTC, dong77 commented on contracts/EmployeeTokenOwnershipPlan2020.sol
> +        return records[recipient].rewarded.mul(block.timestamp.sub(vestStart)) / vestPeriod;
@kongliangzhong Please find out when will our current plan fully vestd, so all people need to know they need to withdraw before that date.

2021-02-19 06:48 UTC, kongliangzhong commented on contracts/EmployeeTokenOwnershipPlan2020.sol
> +        return records[recipient].rewarded.mul(block.timestamp.sub(vestStart)) / vestPeriod;
OK, will do

2021-02-19 14:30 UTC, dong77 requested changes

2021-02-19 14:30 UTC, dong77 commented on contracts/BaseTokenOwnershipPlan.sol
> +    uint public vestStart;
these two can be immutable

2021-02-19 14:30 UTC, dong77 commented on contracts/CancellableEmployeeTokenOwnershipPlan.sol
>      function changeMemberAddress(address oldAddr, address newAddr)
updateRecipient and changeMemberAddress can be one single function. Then we need an abstract internal method:

`function canChangeAddressFor(address who) bool`, for the firs contract, this will return `msg.sender == who` and fo the second, concellable contract, this will return `msg.sender == who || msg.sender == owner`

2021-02-19 14:46 UTC, kongliangzhong commented on contracts/BaseTokenOwnershipPlan.sol
> +    uint public vestStart;
They are initialized in the derived contracts so can not be immutable, otherwise a compile error `Not initialized` will throw.

2021-02-19 14:50 UTC, kongliangzhong commented on contracts/CancellableEmployeeTokenOwnershipPlan.sol
>      function changeMemberAddress(address oldAddr, address newAddr)
fixed.

2021-02-19 16:26 UTC, Brechtpd approved these changes

2021-02-20 02:25 UTC, dong77 commented on contracts/CancellableEmployeeTokenOwnershipPlan.sol
> +        uint80[35] memory _amounts = [
再抽象出一个方法：

``` function getInitialDistribution() returns （address[], uint80[]) pure```

2021-02-20 05:01 UTC, merged